# Generated by Django 3.1.7 on 2021-03-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quntitiy',
            new_name='quantity',
        ),
    ]
